title: Hello, world! I'm Cun Yang
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Cun Yang # add your name
author-img: cun-yang.jpg # add your photo
about-author: Hi! I’m Cun. Thanks for checking out my Blog. I am a Software Engineer with seven years programming experience, Now I am seeking for full-time opportunities at Austin, TX.  # add description
social-twitter: backslash112 # add your Twitter handle
social-facebook: backslash112 # add your Facebook handle
social-github: backslash112 # add your Github handle
social-linkedin: cun-yang # add your Linkedin handle
social-email: cun.yang@outlook.com # add your Email address

# Disqus
discus-identifier: cunyang # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
