title: Cun Yang
description: > # this means to ignore newlines until "baseurl:"
  Hi! I’m Cun. Thanks for checking out my Blog. Now I am focusing on Node.js, AWS, and CI/CD with Docker.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Cun Yang # add your name
author-img: carl-yang.jpg # add your photo
about-author: "Hi! I’m Cun. Thanks for checking out my Blog.
  Now I am focusing on Node.js, AWS, and CI/CD with Docker"
social-twitter: backslash112 # add your Twitter handle
# social-facebook: backslash112 # add your Facebook handle
social-medium: backslash112 # add your Facebook handle
social-github: backslash112 # add your Github handle
social-linkedin: cun-yang # add your Linkedin handle
social-email: cun.yang@outlook.com # add your Email address

# Disqus
discus-identifier: cunyang # add your discus identifier

# Tracker
analytics: UA-123155497-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

collections:
  projects:
    output: true
    permalink: /side-projects/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: post
