# Site settings
title: Software Engineer (2011 - present)
email: cun.yang@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Software Engineer with seven years programming experience.
  Now I am seeking for full-time opportunities at Austin, TX.
  Please send me an email if your team need a new member with rich development experience.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://backslash112.github.io/" #"http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: backslash112
github_username:  backslash112
linkedin_username: cun-yang
# Build settings
markdown: kramdown
